//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean CloseHand
        {
            get
            {
                return SteamVR_Actions.default_CloseHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean Calibrate
        {
            get
            {
                return SteamVR_Actions.default_Calibrate;
            }
        }
        
        public virtual SteamVR_Action_Boolean ArmDisarm
        {
            get
            {
                return SteamVR_Actions.default_ArmDisarm;
            }
        }
        
        public virtual SteamVR_Action_Boolean WalkForward
        {
            get
            {
                return SteamVR_Actions.default_WalkForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnLeft
        {
            get
            {
                return SteamVR_Actions.default_TurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TurnRight
        {
            get
            {
                return SteamVR_Actions.default_TurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Crouch
        {
            get
            {
                return SteamVR_Actions.default_Crouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Stand
        {
            get
            {
                return SteamVR_Actions.default_Stand;
            }
        }
        
        public virtual SteamVR_Action_Boolean NewAction
        {
            get
            {
                return SteamVR_Actions.default_NewAction;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
